package com.example.barcodepro;
import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.os.*; import android.view.*; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import androidx.camera.core.*; import androidx.camera.lifecycle.ProcessCameraProvider; import androidx.camera.view.PreviewView; import androidx.core.app.ActivityCompat; import androidx.core.content.ContextCompat; import com.google.common.util.concurrent.ListenableFuture; import com.google.mlkit.vision.barcode.*; import com.google.mlkit.vision.common.InputImage; import org.json.*; import java.io.*; import java.net.*; import java.util.*; import java.util.concurrent.*;
public class MainActivity extends AppCompatActivity { EditText productName,brand,barcode,price,mrp,customer,discount,gst,payment; TextView qty,billList,summary,onlineStatus; int q=1; ArrayList<String> bill=new ArrayList<>(); SharedPreferences sp; ExecutorService ex=Executors.newSingleThreadExecutor();
public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);sp=getSharedPreferences("pos",0);bind();findViewById(R.id.btnPlus).setOnClickListener(v->{q++;qty.setText(""+q);});findViewById(R.id.btnMinus).setOnClickListener(v->{if(q>1)q--;qty.setText(""+q);});findViewById(R.id.btnScan).setOnClickListener(v->scan());findViewById(R.id.btnSave).setOnClickListener(v->save());findViewById(R.id.btnAdd).setOnClickListener(v->add());findViewById(R.id.btnCatalog).setOnClickListener(v->catalog());findViewById(R.id.btnHistory).setOnClickListener(v->history());findViewById(R.id.btnNew).setOnClickListener(v->newBill());findViewById(R.id.btnShare).setOnClickListener(v->share());barcode.setOnFocusChangeListener((v,h)->{if(!h)load();});discount.setOnFocusChangeListener((v,h)->recalc());gst.setOnFocusChangeListener((v,h)->recalc());}
void bind(){productName=findViewById(R.id.productName);brand=findViewById(R.id.brand);barcode=findViewById(R.id.barcode);price=findViewById(R.id.price);mrp=findViewById(R.id.mrp);qty=findViewById(R.id.qty);billList=findViewById(R.id.billList);summary=findViewById(R.id.summary);customer=findViewById(R.id.customer);discount=findViewById(R.id.discount);gst=findViewById(R.id.gst);payment=findViewById(R.id.payment);onlineStatus=findViewById(R.id.onlineStatus);}
void load(){String c=barcode.getText().toString().trim();if(c.isEmpty())return;String s=sp.getString("p_"+c,null);if(s!=null){String[] a=s.split("\\|",-1);productName.setText(a[0]);brand.setText(a[1]);price.setText(a[2]);mrp.setText(a[3]);onlineStatus.setText("✓ Local catalog match");}else lookup(c);}
void lookup(String code){onlineStatus.setText("Online lookup…");ex.execute(()->{try{URL u=new URL("https://world.openfoodfacts.org/api/v3/product/"+URLEncoder.encode(code,"UTF-8")+".json?fields=product_name,product_name_en,brands");HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(5000);c.setReadTimeout(5000);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder(),z;while((z=r.readLine())!=null)s.append(z);JSONObject p=new JSONObject(s.toString()).optJSONObject("product");runOnUiThread(()->{if(p!=null){productName.setText(p.optString("product_name",p.optString("product_name_en","")));brand.setText(p.optString("brands",""));onlineStatus.setText("✓ Online product found");}else onlineStatus.setText("Online: not found");});}catch(Exception e){runOnUiThread(()->onlineStatus.setText("Offline / not found"));}});}
void save(){String c=barcode.getText().toString().trim(),n=productName.getText().toString().trim();if(c.isEmpty()||n.isEmpty()||price.getText().toString().trim().isEmpty()){toast("Barcode, product name & price required");return;}sp.edit().putString("p_"+c,n+"|"+brand.getText()+"|"+price.getText()+"|"+mrp.getText()).apply();toast("Saved in local catalog ✓");}
void add(){double p=num(price);if(p<=0){toast("Enter selling price");return;}bill.add(productName.getText()+" × "+q+" = ₹"+m(p*q));render();q=1;qty.setText("1");recalc();}
void render(){StringBuilder s=new StringBuilder();for(int i=0;i<bill.size();i++)s.append(i+1).append(". ").append(bill.get(i)).append("\n");billList.setText(s.length()==0?"No items yet":s.toString());}
void recalc(){double sub=0;for(String x:bill){int k=x.lastIndexOf("₹");if(k>=0)try{sub+=Double.parseDouble(x.substring(k+1).trim());}catch(Exception e){}}double d=sub*num(discount)/100,tax=sub-d,g=tax*num(gst)/100;summary.setText("Subtotal: ₹"+m(sub)+"\nDiscount: ₹"+m(d)+"\nGST: ₹"+m(g)+"\nTOTAL: ₹"+m(tax+g));}
double num(EditText e){try{return Double.parseDouble(e.getText().toString());}catch(Exception e2){return 0;}}String m(double x){return String.format(Locale.US,"%.2f",x);}void newBill(){bill.clear();render();productName.setText("");brand.setText("");barcode.setText("");price.setText("");mrp.setText("");q=1;qty.setText("1");recalc();toast("New bill ready");}
void share(){String t="BARCODE BILLER PRO\nCustomer: "+customer.getText()+"\n\n"+billList.getText()+"\n"+summary.getText()+"\nPayment: "+payment.getText();Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,t);startActivity(Intent.createChooser(i,"Share Bill"));sp.edit().putString("h_"+System.currentTimeMillis(),t).apply();}
void catalog(){ArrayList<String>a=new ArrayList<>();for(String k:sp.getAll().keySet())if(k.startsWith("p_"))a.add(k.substring(2));new AlertDialog.Builder(this).setTitle("Local Catalog").setItems(a.toArray(new String[0]),(d,w)->{barcode.setText(a.get(w));load();}).setNegativeButton("Close",null).show();}
void history(){ArrayList<String>a=new ArrayList<>();for(Map.Entry<String,?>e:sp.getAll().entrySet())if(e.getKey().startsWith("h_"))a.add((String)e.getValue());new AlertDialog.Builder(this).setTitle("Bill History").setMessage(a.isEmpty()?"No history":String.join("\n\n----------------\n\n",a)).setPositiveButton("OK",null).show();}
void scan(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.CAMERA},8);return;}Dialog d=new Dialog(this);PreviewView pv=new PreviewView(this);d.setContentView(pv);d.show();ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider cp=f.get();Preview pr=new Preview.Builder().build();pr.setSurfaceProvider(pv.getSurfaceProvider());ImageAnalysis an=new ImageAnalysis.Builder().setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).build();BarcodeScanner sc=BarcodeScanning.getClient();an.setAnalyzer(ex,img->{android.media.Image mi=img.getImage();if(mi==null){img.close();return;}InputImage ii=InputImage.fromMediaImage(mi,img.getImageInfo().getRotationDegrees());sc.process(ii).addOnSuccessListener(bs->{if(!bs.isEmpty()){String raw=bs.get(0).getRawValue();runOnUiThread(()->{barcode.setText(raw);load();d.dismiss();});}}).addOnCompleteListener(x->img.close());});cp.unbindAll();cp.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,pr,an);}catch(Exception e){toast("Scanner error");}},ContextCompat.getMainExecutor(this));}
void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}}
